config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login',to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  resources :users
  get 'signup', to: 'users#new'

  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true

  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: {minimum: 3, maximum: 15},
          uniqueness: {case_sensetive: false}
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custom_display
    @users = User.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast("chatroom_channel",
                {mod_message: message_render(message)})
    end
  end

  private

  def message_params
      params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in successfully"
      redirect_to root_path
    else
      flash.now[:error] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]


  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the message me app #{@user.username}, you have successfully signed up"
      redirect_to root_path
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
      if @user.update(user_params)
        flash[:notice] = "Your account information was successfully updated!"
        redirect_to @user
      else
        render 'new'
      end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account successfully deleted"
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own account"
        redirect_to @user
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="gamepad icon"></i>
  <div class="content">
    Say something!
    <div class="sub header">Try to expand your social circle and make new friends!</div>
  </div>
</h2>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>

      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true, method: "POST") do |f|%>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, placeholder: "Enter a message"%>
              <%= f.button '<i class="bordered inverted edit icon"></i>'.html_safe%>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <%@users.each do |user|%>
          <div class="item">
            <%=user.username%>
          </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<%end%>

app/views/layouts/_navigation.html.erb
<div class="ui inverted small menu">
  <div class="ui container">
    <%= link_to 'Chatroom', root_path, class: "item"%>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <%if logged_in? %>
            <%= link_to "Profile", user_path(id: current_user.id), class: "item" %>
            <%= link_to "Logout", logout_path, method: :delete, class: "item" %>
          <%else%>
            <%= link_to "Log in", login_path, class: "item"%>
            <%= link_to "Sign up", signup_path, class: "item" %>
          <%end%>
        </div>
      </div>
      <%if !logged_in? %>
        <div class="item">
            <%= link_to "Log in", login_path, class: "ui primary button"%>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'layouts/navigation'%>
    <div class="ui container">
      <%=render 'layouts/messages'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
       <em><%=message.user.username%></em>: <%= message.body%>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="column">
  <%= form_with(model: @user, local: true, html: {class: "ui form", role: "form"}) do |f| %>
    <div class="field">
      <%= f.label :username, "Username" %>
      <div class="ui left icon input">
        <%= f.text_field :username, placeholder: "Username" %>
        <i class="user icon"></i>
      </div>
    </div>
    <div class="field">
      <%= f.label :password, "Password" %>
      <div class="ui left icon input">
        <%= f.password_field :password, placeholder: "Password" %>
        <i class="lock icon"></i>
      </div>
    </div>
    <%= f.submit(@user.new_record? ? "Signup" : "Update your information", class: "ui black submit button") %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2 class="ui center aligned icon header">
	<em>MessageMe</em>
</h2>

<h2 class="ui center aligned icon header">
	<i class="gamepad icon"></i>
</h2>

<h4 class="ui center aligned header">
	<div class="ui message">Edit your profile information.</div>
</h4>

<div class="ui placeholder raised segment">
  <div class="ui one column very relaxed stackable grid">
  	<%= render 'form' %>
  </div>
</div>

app/views/users/new.html.erb
<h3 class="ui center aligned icon header">
	Welcome to <em>MessageMe</em></h3>
  <h2 class="ui center aligned icon header"><i class="gamepad icon"></i></h2>
<h4 class="ui center aligned header">
	<div class="ui message">Please Sign up to continue. Provide valid e-mail for password reset.
	</div>
</h4>

<div class="ui placeholder raised segment">
  <div class="ui one column very relaxed stackable grid">
  	<%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<h4 class="ui center aligned header">
  User information
</h4>
<table class="ui single line table black">
  <thead>
    <tr>
      <th>Userame</th>
      <th>Registration Date</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @user.username %></td>
      <td><%= @user.created_at.strftime("%F") %></td>
    </tr>
  </tbody>
</table>
<div class="ui center aligned container">
  <div class="ui buttons">
    <%= link_to 'Update information', edit_user_path(@user), class: "ui black button" %>
      <div class="or"></div>
    <%= link_to 'Delete your profile', user_path(@user), method: :delete, class: "ui grey button", data: { confirm: "This action is irreversible! Are you sure?"} %>
  </div>
</div>